### ISSUE TITLE
【改进建议】打开容器时检查领地权限

### ISSUE THREAD

**Issue by JiangQiYan713** [SlimefunGuguProject/SlimeCustomizer#1]
## Description
其他有关slimefun的容器会被领地识别，非领地成员无法打开
但是slimecustomizer机器可以被随意打开

## Steps to reproduce the Issue (Required)

https://user-images.githubusercontent.com/91627081/165006780-924645b8-9806-493f-9cbe-fc55216429ab.mp4

## Expected behavior (Required)
需要对应的领地权限，玩家才能打开slimecustomizer的容器和机器

或者允许自定义检查领地权限

## Config Files

 - Minecraft Version:git-Paper-287 1.18.2
 - CS-CoreLib Version:?
 - Slimefun Version:2022.04-release
 - Plugin Version:vBuild 3 zh-CN(SlimefunGuguProject)(git 525aacb)
 - Residence Version:5.0.1.5

**Comment by ybw0014** [comment]
sfc的机器是遵循粘液本体的保护模块的，需要交互权限才能打开。
