### ISSUE TITLE
直接输入/sc categories产生报错（可能是空指针？）

### ISSUE THREAD

**Issue by haiman233** [SlimefunGuguProject/SlimeCustomizer#10]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeCustomizer/issues)，且没有找到相同的问题

### 问题描述

![06158A2CC95C7F9CFF76D9090DD7A5E2](https://user-images.githubusercontent.com/83174104/229345375-48fae0df-31b4-4533-a315-16dc983e06a6.jpg)

### 复现步骤

打开游戏，输入/sc categories

### 预期行为

暂时还不知道这指令是干啥用的

### 服务端软件

Purpur

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

粘液最新版

### 插件版本

Build 18

**Comment by ybw0014** [comment]
啧，作者没加分页，分类超过54个时就报错了

**Comment by ybw0014** [comment]
我选择扔给作者解决
