### ISSUE TITLE
不知道是啥玩意的报错 bs重制版

### ISSUE THREAD

**Issue by uouiiu** [SlimefunGuguProject/SlimeCustomizer#13]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SlimeCustomizer/issues)，且没有找到相同的问题

### 问题描述

Error Generated: 2023-05-23-21-26

Java Environment:
Operating System: Windows Server 2022
Java Version: 17.0.6

Server Software: Purpur
Build: git-Purpur-1976 (MC: 1.19.4)
Minecraft v1.19.4-R0.1-SNAPSHOT

Slimefun Environment:
Slimefun v20608c9-DEV
Caused by: SlimeCustomizer vBuild 23 zh-CN(SlimefunGuguProject) (git e408a5a)

Installed Addons (44)

SlimyTreeTaps Build 2 zh-CN(ybw0014) (git 8a58b9f)
GuizhanLibPlugin Build 22 (git 2f447db)
CMILib 1.2.5.3
LiteXpansion Build 23 zh-CN(ybw0014) (git 95150d0)
ExoticGarden Build 14 zh-CN(ybw0014) (git 0f8c287)
InfinityExpansion Build 5 zh-CN(SlimefunGuguProject) (git 018bfe1)
CMI 9.5.0.8
DynaTech Build 46 zh-CN(ybw0014) (git 9bf98ff)
SimpleMaterialGenerators Build 5 zh-CN(SlimefunGuguProject) (git e05d257)
HeadLimiter Build 6 zh-CN(ybw0014) (git 008aebe)
Netheopoiesis MODIFIED
Residence 5.1.1.2
PotionExpansion Build 1 zh-CN(baoad) (git b25bd1d)
FluffyMachines Build 17 zh-CN(baoad) (git 1982d30)
TranscEndence Build 6 zh-CN(baoad) (git 12c5713)
GuizhanCraft Build 9 (ybw0014) (git fe31b45)
Endrex Build 1 zh-CN(SlimefunGuguProject) (git 23dbf5e)
Liquid Build 2 zh-CN(baoad) (git e03ec2f)
SlimyBees Build 1 zh-CN(SlimefunGuguProject) (git 810abc0)
EcoPower Build 1 zh-CN(ybw0014) (git eca8ab1)
SlimefunWarfare Build 9 zh-CN(ybw0014) (git 91bf6cf)
Bump Build 32 zh-CN(SlimefunGuguProject) (git 4923d02)
AlchimiaVitae Build 8 zh-CN(ybw0014) (git 848dc33)
FNAmplifications Build 91 zh-CN(buiawpkgew1) (git 8652f8c)
SlimefunItemExpansion 1.0.2
FoxyMachines Build 19 zh-CN(ybw0014) (git dc67d11)
Gastronomicon 1.0.1
CrystamaeHistoria Build 32 zh-CN(SlimefunGuguProject) (git 3b117aa)
Networks 1.2.0
GlobalWarming Build 5 zh-CN(ybw0014) (git 725aebe)
Wildernether Build 4 zh-CN(SlimefunGuguProject) (git 32218bd)
UltimateGenerators Build 9 RC-27(LittleQiu233) (git 453f245)
Supreme Build 15 zh-CN(SlimefunGuguProject) (git 50ee209)
SpiritsUnchained Build 5 zh-CN(SlimefunGuguProject) (git f64a11b)
SlimeHUDPlus 1.2.7
SlimeGlue 1.0.2-b262a4a
SimpleUtils Build 1 zh-CN(baoad) (git 721f4c9)
SfChunkInfo Build 8 zh-CN(ybw0014) (git 4ade4ca)
MiniBlocks Build 2 zh-CN(SlimefunGuguProject) (git bb80911)
SlimeCustomizer Build 23 zh-CN(SlimefunGuguProject) (git e408a5a)
Cultivation 0.0.1
MyFirstAddon Build 1 zh-CN(SlimefunGuguProject) (git 82208d8)
BedrockTechnology Build 41 zh-CN(CTimet) (git 5dccd8e)
AureliumSkills Beta 1.3.18
Installed Plugins (110):

ViaVersion 4.6.2
LuckPerms 5.4.40
PlaceholderAPI 2.11.3
ProtocolLib 5.0.0
Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
HolographicDisplays 3.0.2
Citizens 2.0.31-SNAPSHOT (build 3011)
WorldEdit 7.2.14+6360-094b734
BentoBox 1.23.1
Slimefun https://github.com/StarWishsama/Slimefun4/commit/20608c94759900b64026e71eb7602ef4bfc61131-DEV
eco 6.60.4
Multiverse-Core 4.3.1-b861
SlimyTreeTaps Build 2 zh-CN(ybw0014) (git 8a58b9f)
GuizhanLibPlugin Build 22 (git 2f447db)
EcoEnchants 10.14.0
MyPet 3.12
CMILib 1.2.5.3
MythicMobs 5.2.6-0819d467
LiteXpansion Build 23 zh-CN(ybw0014) (git 95150d0)
Jobs 5.1.3.0
ExoticGarden Build 14 zh-CN(ybw0014) (git 0f8c287)
InfinityExpansion Build 5 zh-CN(SlimefunGuguProject) (git 018bfe1)
CMI 9.5.0.8
PlayerTask 1.14.5
PlayerTitle 3.3.8
DynaTech Build 46 zh-CN(ybw0014) (git 9bf98ff)
SimpleMaterialGenerators Build 5 zh-CN(SlimefunGuguProject) (git e05d257)
HeadLimiter Build 6 zh-CN(ybw0014) (git 008aebe)
Netheopoiesis MODIFIED
ViaBackwards 4.6.1
Residence 5.1.1.2
PlayerGuild 1.8.6
PotionExpansion Build 1 zh-CN(baoad) (git b25bd1d)
FluffyMachines Build 17 zh-CN(baoad) (git 1982d30)
TranscEndence Build 6 zh-CN(baoad) (git 12c5713)
GuizhanCraft Build 9 (ybw0014) (git fe31b45)
Endrex Build 1 zh-CN(SlimefunGuguProject) (git 23dbf5e)
Liquid Build 2 zh-CN(baoad) (git e03ec2f)
SlimyBees Build 1 zh-CN(SlimefunGuguProject) (git 810abc0)
EcoPower Build 1 zh-CN(ybw0014) (git eca8ab1)
SlimefunWarfare Build 9 zh-CN(ybw0014) (git 91bf6cf)
Bump Build 32 zh-CN(SlimefunGuguProject) (git 4923d02)
AlchimiaVitae Build 8 zh-CN(ybw0014) (git 848dc33)
FNAmplifications Build 91 zh-CN(buiawpkgew1) (git 8652f8c)
SlimefunItemExpansion 1.0.2
FoxyMachines Build 19 zh-CN(ybw0014) (git dc67d11)
Gastronomicon 1.0.1
CrystamaeHistoria Build 32 zh-CN(SlimefunGuguProject) (git 3b117aa)
Networks 1.2.0
GlobalWarming Build 5 zh-CN(ybw0014) (git 725aebe)
DecentHolograms 2.8.1
NexEngine 2.2.10 build-11/05/2023
spark 1.10.39
VoidWorld 1.0
TimeMessageDe 1.0-SNAPSHOT
LaggRemover 2.0.6
LuckTextures 1.2
Wildernether Build 4 zh-CN(SlimefunGuguProject) (git 32218bd)
ViaRewind 2.0.2
UltimateGenerators Build 9 RC-27(LittleQiu233) (git 453f245)
TrChat 2.0.0-PRE-38
TimeIsMoney 1.9.6.22
TAB 3.3.2
Supreme Build 15 zh-CN(SlimefunGuguProject) (git 50ee209)
SpiritsUnchained Build 5 zh-CN(SlimefunGuguProject) (git f64a11b)
SlimeHUDPlus 1.2.7
SlimeGlue 1.0.2-b262a4a
SimpleUtils Build 1 zh-CN(baoad) (git 721f4c9)
Shopkeepers 2.16.5
SfChunkInfo Build 8 zh-CN(ybw0014) (git 4ade4ca)
QuickShop 5.1.2.0
PlugManX 2.2.7
PlayerTop 1.2.6
PlayerKits 2.25.1
PlayerIntensify 2.0.7
NoPlugins 8.1
MiniBlocks Build 2 zh-CN(SlimefunGuguProject) (git bb80911)
MineResetLite 4.17.0
LiteSignIn 1.7.0.0
LevelledMobs 3.10.0 b752
Invero 1.0.6
InfinityStones 1.47
ILoreEdit 2.5.1
GlobalMarketPlus 1.1.6.0
SlimeCustomizer Build 23 zh-CN(SlimefunGuguProject) (git e408a5a)
FartherViewDistance 9.7.7
ExcellentCrates 4.2.0
EClean 1.0.14
DeluxeMenus 1.13.7-Release
Dantiao EX-31
CustomCobbleGen 1.5.0
Cultivation 0.0.1
CtOnlineReward 0.1.9
CoreProtect 21.2
ChineseName 2.2-pre-4
MyFirstAddon Build 1 zh-CN(SlimefunGuguProject) (git 82208d8)
BlockParticles 1.11.1-RELEASE
BedrockTechnology Build 41 zh-CN(CTimet) (git 5dccd8e)
AureliumSkills Beta 1.3.18
AntiBuild 1.3.2-SNAPSHOT
AnimatedScoreboard 0.2.7
libreforge 4.14.0
BentoBox-Bank 1.5.0
BentoBox-Biomes 2.1.1
BentoBox-BSkyBlock 1.16.1
BentoBox-Challenges 1.2.0
BentoBox-Level 2.10.0
BentoBox-Likes 2.3.1
BentoBox-Visit 1.6.0
BentoBox-Warps 1.13.0
Block Info:
World: bskyblock_world
X: 2398
Y: 35
Z: -767
Material: PLAYER_HEAD
Block Data: org.bukkit.craftbukkit.v1_19_R3.block.impl.CraftSkullPlayer
State: org.bukkit.craftbukkit.v1_19_R3.block.CraftSkull

Ticker-Info:
Type: Indirect (Energy Network)

Slimefun Data:
ID: HAIMAN_EXAMPLE_GENERATOR
Is data loaded: true
Inventory: true
Data:

Stacktrace:

java.lang.NoSuchMethodError: 'int io.ncbpfluffybear.slimecustomizer.objects.SCAGenerator.getCharge(org.bukkit.Location, me.mrCookieSlime.CSCoreLibPlugin.Configuration.Config)'
at SlimeCustomizer-Build 23 zh-CN(SlimefunGuguProject) (git e408a5a) (2).jar//io.ncbpfluffybear.slimecustomizer.objects.SCAGenerator.getGeneratedOutput(SCAGenerator.java:164)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.core.attributes.EnergyNetProvider.getGeneratedOutput(EnergyNetProvider.java:45)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.core.networks.energy.EnergyNet.tickAllGenerators(EnergyNet.java:251)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.core.networks.energy.EnergyNet.tick(EnergyNet.java:157)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator.tick(EnergyRegulator.java:84)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.implementation.items.electric.EnergyRegulator$3.tick(EnergyRegulator.java:77)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:169)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:156)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:123)
at Slimefun-v20608c9-DEV.jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:100)
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

### 复现步骤

不知道，看文件发现的报错

### 预期行为

我不到啊，好像是一些机器没办法发电，可以发电但是进不了存储

### 服务端软件

Purpur

### Minecraft 版本

1.19.4

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun-v20608c9-DEV bs重制版，最新的那个

### 插件版本

Slimefun-v20608c9-DEV bs重制版，最新的那个

**Comment by ybw0014** [comment]
发一下发电机配置，看上去可能是配置有问题

**Comment by shixinzia** [comment]
emm,拓芙也遇见了这个问题:(

**Comment by shixinzia** [comment]
HAIMAN_EXAMPLE_GENERATOR:
  category: slime_customizer_generator
  generator-name: '&b&l空岛发电机'
  generator-lore:
  - '&7空岛福利型发电机！'
  block-type: SKULL281cc64b045b18a3a419c595ad658f6ce2c599949477afe42a6b587aa315bf
  progress-bar-item: FLINT_AND_STEEL
  stats:
    energy-production: 10
    energy-buffer: 1000
  crafting-recipe-type: ENHANCED_CRAFTING_TABLE
  crafting-recipe:
    '1':
      type: VANILLA
      id: IRON_BLOCK
      amount: 1
    '2':
      type: NONE
      id: N/A
      amount: 1
    '3':
      type: VANILLA
      id: IRON_BLOCK
      amount: 1
    '4':
      type: VANILLA
      id: IRON_BLOCK
      amount: 1
    '5':
      type: SLIMEFUN
      id: COAL_GENERATOR
      amount: 1
    '6':
      type: VANILLA
      id: IRON_BLOCK
      amount: 1
    '7':
      type: VANILLA
      id: IRON_BLOCK
      amount: 1
    '8':
      type: VANILLA
      id: IRON_BLOCK
      amount: 1
    '9':
      type: VANILLA
      id: IRON_BLOCK
      amount: 1
  recipes:
    '1':
      time-in-seconds: 2
      input:
        type: VANILLA
        id: COBBLESTONE
        amount: 1
      output:
        type: NONE
        id: N/A
        amount: N/A
    '2':
      time-in-seconds: 12
      input:
        type: VANILLA
        id: ROTTEN_FLESH
        amount: 2
      output:
        type: VANILLA
        id: DIRT
        amount: 1

**Comment by shixinzia** [comment]
[2023-06-02-20-14.txt](https://github.com/SlimefunGuguProject/SlimeCustomizer/files/11635340/2023-06-02-20-14.txt)

**Comment by shixinzia** [comment]
@ybw0014 :)

**Comment by shixinzia** [comment]
ERROR: https://paste.guizhanss.net/28eqz
发电机: https://paste.guizhanss.net/gXW1m

**Comment by StarWishsama** [comment]
missing `AGenerator.getCharge(org.bukkit.Location, me.mrCookieSlime.CSCoreLibPlugin.Configuration.Config)`?

**Comment by ybw0014** [comment]
请在此下载测试版本进行测试：https://cloud.ybw0014.net/s/N6Ir
